[workspace]
members = [
    "game",   # contains game logic
    "server", # contains websocket server
    "client", # contains client code
    "shared"  # contains shared code
]

resolver = "2"

[profile.release]
opt-level = "s"
