// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Item } from "./Item";
import type { Position } from "./Position";
import type { Team } from "./Team";

export type Flag = { position: Position, team: Team, item: Item, };
