// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerAssigned } from "./PlayerAssigned";
import type { Snapshot } from "./Snapshot";

export type GameMessage = { "Snapshot": Snapshot } | { "PlayerAssigned": PlayerAssigned };
