// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Team } from "./Team";
import type { Velocity } from "./Velocity";

export type Input = { "CreatePlayer": { id: string, team: Team, } } | { "PlayerMove": { player_id: string, velocity: Velocity, } };
