// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Team } from "./Team";
import type { Velocity } from "./Velocity";

export type Input = { "createPlayer": { id: string, team: Team, } } | { "playerMove": { playerId: string, velocity: Velocity, } } | { "removePlayer": { id: string, } } | { "playerMelee": { player_id: string, } };
