// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Metadata } from "./Metadata";
import type { Position } from "./Position";
import type { Team } from "./Team";
import type { Velocity } from "./Velocity";

export type Player = { metadata: Metadata, position: Position, velocity: Velocity, team: Team, melee_active: boolean, };
