// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Team } from "./Team";

export type PlayerAssigned = { player_id: bigint, team: Team, };
