// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Flag } from "./Flag";
import type { Player } from "./Player";

export type Snapshot = { players: Array<Player>, flags: Array<Flag>, };
