// Public types that are used in the game, needed by client
// And generated by ts-rs

use std::collections::HashMap;

use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(TS, Debug, Clone, Copy, Serialize, Deserialize)]
#[ts(export)]
pub struct Radius {
    pub value: f32,
}

#[derive(TS, Debug, Clone, Copy, Serialize, Deserialize)]
#[ts(export)]
pub struct Velocity {
    pub dx: f32,
    pub dy: f32,
}

// Position component
#[derive(TS, Debug, Clone, Copy, Serialize, Deserialize)]
#[ts(export)]
pub struct Position {
    pub x: f32,
    pub y: f32,
}

// Melee
#[derive(TS, Debug, Clone, Copy, Serialize, Deserialize)]
#[ts(export)]
pub struct Melee {
    pub active: bool,
    pub cooldown: f32,
    pub max_cooldown: f32,
}

pub const MELEE_COOLDOWN: f32 = 0.75;
pub const MELEE_DURATION: f32 = 0.2;
pub const MELEE_SPEED_MULTIPLIER: f32 = 90.0; // How much faster the player moves during attack
pub const MELEE_COOLDOWN_SPEED_MULTIPLIER: f32 = 0.5;

// Team component
#[derive(TS, Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Hash)]
#[ts(export)]
#[serde(rename_all = "camelCase")]
pub enum Team {
    Red,
    Blue,
}

// Player component
#[derive(TS, Debug, Clone, Serialize, Deserialize)]
#[ts(export)]
pub struct Metadata {
    pub id: String,
}

// Flag component
#[derive(TS, Debug, Clone, Serialize, Deserialize)]
#[ts(export)]
pub struct Item {
    pub held_by: Option<String>,
}

#[derive(Debug, Serialize, Deserialize, Clone, TS)]
#[ts(export)]
#[serde(rename_all = "camelCase")]
pub enum Input {
    #[serde(rename_all = "camelCase")]
    CreatePlayer {
        id: String,
        team: Team,
    },
    #[serde(rename_all = "camelCase")]
    PlayerMove {
        player_id: String,
        velocity: Velocity,
    },
    #[serde(rename_all = "camelCase")]
    RemovePlayer {
        id: String,
    },
    PlayerMelee {
        player_id: String,
    },
}

#[derive(Debug, Serialize, Deserialize, Clone, TS)]
#[ts(export)]
pub struct Player {
    pub metadata: Metadata,
    pub position: Position,
    pub velocity: Velocity,
    pub team: Team,
    pub melee_active: bool,
}

#[derive(Debug, Serialize, Deserialize, Clone, TS)]
#[ts(export)]
pub struct Flag {
    pub position: Position,
    pub team: Team,
    pub item: Item,
}

// All the data that needs to be sent to the client to render the game
#[derive(Debug, Serialize, Deserialize, Clone, TS)]
#[ts(export)]
pub struct Snapshot {
    pub players: Vec<Player>,
    pub flags: Vec<Flag>,
    pub score: HashMap<Team, u32>,
}
