// Public types that are used in the game, needed by client
// And generated by ts-rs

use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(TS, Debug, Clone, Copy, Serialize, Deserialize)]
#[ts(export)]
pub struct Radius {
    pub value: f32,
}

#[derive(TS, Debug, Clone, Copy, Serialize, Deserialize)]
#[ts(export)]
pub struct Velocity {
    pub dx: f32,
    pub dy: f32,
}

// Position component
#[derive(TS, Debug, Clone, Copy, Serialize, Deserialize)]
#[ts(export)]
pub struct Position {
    pub x: f32,
    pub y: f32,
}

// Team component
#[derive(TS, Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[ts(export)]
#[serde(rename_all = "camelCase")]
pub enum Team {
    Red,
    Blue,
}

// Player component
#[derive(TS, Debug, Clone, Serialize, Deserialize)]
#[ts(export)]
pub struct Metadata {
    pub id: String,
}

// Flag component
#[derive(TS, Debug, Clone, Serialize, Deserialize)]
#[ts(export)]
pub struct Item {
    pub held_by: Option<String>,
}

#[derive(Debug, Serialize, Deserialize, Clone, TS)]
#[ts(export)]
#[serde(rename_all = "camelCase")]
pub enum Input {
    #[serde(rename_all = "camelCase")]
    CreatePlayer { id: String, team: Team },
    #[serde(rename_all = "camelCase")]
    PlayerMove {
        player_id: String,
        velocity: Velocity,
    },
    #[serde(rename_all = "camelCase")]
    RemovePlayer { id: String },
}

#[derive(Debug, Serialize, Deserialize, Clone, TS)]
#[ts(export)]
pub struct Player {
    pub metadata: Metadata,
    pub position: Position,
    pub velocity: Velocity,
    pub team: Team,
}

#[derive(Debug, Serialize, Deserialize, Clone, TS)]
#[ts(export)]
pub struct Flag {
    pub position: Position,
    pub team: Team,
    pub item: Item,
}

// All the data that needs to be sent to the client to render the game
#[derive(Debug, Serialize, Deserialize, Clone, TS)]
#[ts(export)]
pub struct Snapshot {
    pub players: Vec<Player>,
    pub flags: Vec<Flag>,
}
